### ISSUE TITLE
create components from notion

### ISSUE THREAD

**Issue by Eikix** [rkdud007/chess-dojo#2]
https://kakarotlabs.notion.site/Hackathon-Project-LambdaZkWeek-CLI-Chess-on-Dojo-3ab600ff96f64b72af4c5c8edd70c787?pvs=4

**Comment by rkdud007** [comment]
https://github.com/rkdud007/chess-dojo/commit/5e5e13340fe532d89643694679da2c37bafa5919
@Eikix

**Comment by Eikix** [comment]
done

**Comment by Eikix** [comment]
reopening as we forked dojo starter

**Comment by Eikix** [comment]
done
